Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -35,12 +35,20 @@ jobs:
           python -m pip install --upgrade pip
           pip install -r requirements.txt # Instala las dependencias de tu proyecto
 
-      # 4. Ejecutar script de recolección de datos
+      # 4. Verificar existencia del script collector.py
+      - name: Verificar existencia del script collector.py
+        run: |
+          if [ ! -f ProyectoV_2025/static/models/collector.py ]; then
+            echo "Error: El archivo collector.py no existe en la ruta especificada."
+            exit 1
+          fi
+
+      # 5. Ejecutar script de recolección de datos
       - name: Ejecutar script de recolección de datos
         run: |
           python ProyectoV_2025/static/models/collector.py 
 
-      # 5. Commit y subir cambios
+      # 6. Commit y subir cambios
       - name: Commit y subir cambios
         run: |
           git config --local user.email "github-actions@github.com"
